name: Deployment

on:
  push:
    branches:
      - website
      - chore/add-ovh-deployment
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event.action != 'closed' && github.event.action != 'labeled')
    uses: ./.github/workflows/ovh.yaml
    with:
      environment_name: ${{ github.event_name == 'push' && 'production' || format('pull/{0}', github.event.pull_request.number) }}
      environment_url: https://mixxx.acolombier.dev${{ github.event_name == 'pull_request' && format('/preview/pull/{0}', github.event.pull_request.number) || '' }}
      target: ${{ github.event_name == 'pull_request' && format('preview/pull/{0}', github.event.pull_request.number) || '' }}
      base:  ${{ github.event_name == 'pull_request' && format('/preview/pull/{0}', github.event.pull_request.number) || '' }}
      action: deploy
    secrets: inherit

  cleanup:
    if: |
      github.event_name == 'pull_request' && (github.event.action == 'closed' || contains(github.event.pull_request.labels.*.name, 'stale'))
    uses: ./.github/workflows/ovh.yaml
    with:
      environment_name: ${{ format('pull/{0}', github.event.pull_request.number) }}
      target: ${{ format('preview/pull/{0}', github.event.pull_request.number) }}
      action: teardown
    secrets: inherit
